#!/usr/bin/env python3
from description_utils import SUPPORTED_ALGORITHMS_INLINE, SUPPORTED_ALGORITHMS_QUOTED

print('SUPPORTED_ALGORITHMS_INLINE:', repr(SUPPORTED_ALGORITHMS_INLINE))
print('SUPPORTED_ALGORITHMS_QUOTED:', repr(SUPPORTED_ALGORITHMS_QUOTED))