from utils import stderr_print
#!/usr/bin/env python3
from description_utils import SUPPORTED_ALGORITHMS_INLINE, SUPPORTED_ALGORITHMS_QUOTED

stderr_print('SUPPORTED_ALGORITHMS_INLINE:', repr(SUPPORTED_ALGORITHMS_INLINE))
stderr_print('SUPPORTED_ALGORITHMS_QUOTED:', repr(SUPPORTED_ALGORITHMS_QUOTED))