input {
  file {
    path => "/logs/pagayalogs.txt"
    start_position => "beginning"
    sincedb_path => "/dev/null"     
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:ts} %{GREEDYDATA:msg}" }
    tag_on_failure => []
  }
  date {
    match  => [ "ts", "yyyy-MM-dd HH:mm:ss.SSS Z" ]
    target => "@timestamp"
  }
  mutate {
    replace      => { "message" => "%{msg}" }
    remove_field => [ "ts", "msg", "@version", "path", "host", "tags" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"] 
    index => "logspagaya"
  }
}