input {
  elasticsearch {
    id => {{id}}
    hosts => [ "{{es_host}}" ]
    query_type => "esql"
    query => "{{{query}}}"                # triple mustache: no re-escapa
    schedule => "{{cron}}"                # ej: */5 * * * *
  }
}

output {
  mongodb {
    uri => "{{mongo_uri}}"                # ideal: venir de env/secret
    database => "{{mongo_db}}"
    collection => "{{mongo_collection}}"
    isodate => true
  }
  stdout { codec => rubydebug }
}