# Docker environment configuration
spring.data.mongodb.uri=mongodb://admin:1q2w3E*@mongodb:27017/?authSource=admin
spring.elasticsearch.uris=http://elasticsearch-dataset:9200
app.anomalies-insights.api.url=http://anomalies-insights:8081/api
